
- name: populate database
  shell: |
    cd tigase-server
    scripts/db-create-mysql.sh -y {{ mysql_user_name }} {{ mysql_user_password }} {{ mysql_user_name }} >/dev/null || exit 0
    cd ..

    # create kontalk database objects
    for SCRIPT in tigase-extension/data/*.sql;
    do
        mysql -u{{ mysql_user_name }} -p{{ mysql_user_password }} kontalk < ${SCRIPT}
    done
